/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.dao.EstudianteDao;
import controlador.listas.ListaSimple;
import javax.swing.JOptionPane;
import vista.modelo.ModeloTablaEstudiante;

/**
 *
 * @author joe
 */
public class Frm_estudiante extends javax.swing.JDialog {

    /**
     * Creates new form Frm_estudiante
     */
    private ModeloTablaEstudiante modelo = new ModeloTablaEstudiante();
    private EstudianteDao ed = new EstudianteDao();

    public Frm_estudiante(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        cargarTabla();        
    }

    private void cargarTabla() {        
        modelo.setLista(ed.ordenar(ed.listar(), ListaSimple.ORDENAR_DESCENDENTE));        
        tbltabla.setModel(modelo);
        tbltabla.updateUI();
    }
    //private void ordenar() {
     //   ed.ordenar();
    //}
    
    private void limpiar() {
        ed.setEstudainte(null);
        txtapellidos.setText("");
        txtcedula.setText("");
        txtcorreo.setText("");
        txtdireccion.setText("");
        txtfono.setText("");
        txtnombres.setText("");
        cargarTabla();
    }

    private void guardar() {
        if (txtcedula.getText().isEmpty() || txtapellidos.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Llene todos los campos", "Error", JOptionPane.ERROR_MESSAGE);
            limpiar();
        } else {
            ed.setEstudainte(null);
            ed.getEstudainte().setApellidos(txtapellidos.getText());
            ed.getEstudainte().setCedula(txtcedula.getText());
            ed.getEstudainte().setCorreo(txtcorreo.getText());
            ed.getEstudainte().setDireccion(txtdireccion.getText());
            ed.getEstudainte().setNombres(txtnombres.getText());
            ed.getEstudainte().setTelefono(txtfono.getText());
            if(ed.guardar()) {
                JOptionPane.showMessageDialog(this, "Se ha guardado correctamente", "OK", JOptionPane.INFORMATION_MESSAGE);
                
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo guardar", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtnombres = new javax.swing.JTextField();
        txtcedula = new javax.swing.JTextField();
        txtapellidos = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfono = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdireccion = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        btn_guardar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbltabla = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Datos del estudiante"));
        jPanel2.setLayout(null);

        jLabel1.setText("NOMBRES:");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(440, 70, 90, 19);

        jLabel2.setText("CEDULA:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(20, 30, 90, 19);

        jLabel3.setText("APELLIDOS:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(20, 70, 90, 19);
        jPanel2.add(txtnombres);
        txtnombres.setBounds(530, 60, 280, 31);
        jPanel2.add(txtcedula);
        txtcedula.setBounds(130, 20, 280, 31);
        jPanel2.add(txtapellidos);
        txtapellidos.setBounds(130, 60, 280, 31);

        jLabel4.setText("DIRECCION:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 160, 90, 19);
        jPanel2.add(txtcorreo);
        txtcorreo.setBounds(130, 100, 280, 31);

        jLabel5.setText("TELEFONO:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(440, 110, 90, 19);
        jPanel2.add(txtfono);
        txtfono.setBounds(530, 100, 280, 31);

        jLabel6.setText("CORREO:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(20, 110, 90, 19);

        txtdireccion.setColumns(20);
        txtdireccion.setLineWrap(true);
        txtdireccion.setRows(5);
        txtdireccion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtdireccion);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(130, 150, 680, 50);

        jButton1.setText("LIMPIAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(400, 220, 110, 33);

        btn_guardar.setText("GUARDAR");
        btn_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_guardarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_guardar);
        btn_guardar.setBounds(250, 220, 110, 33);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(10, 10, 820, 260);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "LISTA DE ESTUDIANTES"));
        jPanel3.setLayout(null);

        tbltabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbltabla);

        jPanel3.add(jScrollPane2);
        jScrollPane2.setBounds(20, 20, 610, 110);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(10, 280, 820, 150);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 840, 450);

        setSize(new java.awt.Dimension(853, 484));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_guardarActionPerformed
        // TODO add your handling code here:
        guardar();
    }//GEN-LAST:event_btn_guardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        limpiar();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frm_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frm_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frm_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frm_estudiante.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Frm_estudiante dialog = new Frm_estudiante(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbltabla;
    private javax.swing.JTextField txtapellidos;
    private javax.swing.JTextField txtcedula;
    private javax.swing.JTextField txtcorreo;
    private javax.swing.JTextArea txtdireccion;
    private javax.swing.JTextField txtfono;
    private javax.swing.JTextField txtnombres;
    // End of variables declaration//GEN-END:variables
}
