/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.servicio.CuentaServicio;
import controlador.servicio.RolServicio;
import javax.swing.JOptionPane;

/**
 *
 * @author joe
 */
public class FrmSesion extends javax.swing.JDialog {

    /**
     * Creates new form FrmSesion
     */
    private RolServicio rs = new RolServicio();
    private CuentaServicio cs = new CuentaServicio();

    public FrmSesion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rs.crearRoles();
    }

    private void inicioSesion() {
        String usurio = txtcorreo.getText();
        String clave = new String(txtclave.getPassword());
        Sesion.setCuenta(cs.inicioSesion(usurio, clave));
        if (Sesion.getCuenta() != null) {
            if (Sesion.getCuenta().getEstado()) {
                Sesion.cargarDatos();
                JOptionPane.showMessageDialog(this, "BIENVENIDO: " + Sesion.getPersona().toString() + "\n " 
                        + "Ha iniciado como: " + Sesion.getRol().toString());
                new Frm_Principal().setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(null, "Cuenta no activa", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Usuario no encontrado", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtcorreo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtclave = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(null);

        jLabel1.setText("Correo:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 20, 110, 19);
        jPanel1.add(txtcorreo);
        txtcorreo.setBounds(80, 20, 190, 31);

        jLabel2.setText("Clave:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 70, 110, 19);
        jPanel1.add(txtclave);
        txtclave.setBounds(80, 70, 190, 31);

        jButton2.setText("ENTRAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(20, 150, 100, 33);

        jButton1.setText("CANCELAR");
        jPanel1.add(jButton1);
        jButton1.setBounds(170, 150, 100, 33);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 320, 210);

        setSize(new java.awt.Dimension(324, 240));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (txtclave.getPassword().length == 0 || txtcorreo.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Llene todo los campos", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            inicioSesion();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmSesion dialog = new FrmSesion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField txtclave;
    private javax.swing.JTextField txtcorreo;
    // End of variables declaration//GEN-END:variables
}
